name: End-to-end tests
on: [push]

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: yarn install
      - run: yarn lint
      - run: yarn cy:run